# samples_per_pixel = 100

camera = { position = [0, 1, 0], direction = 'forward' }

materials = [
	{ colour = 'gray_33' },
	{ colour = 'fuchsia' },
]

planes = [
	#{ material = 0 }
]

spheres = [
	{ material = 0, position=[0 ,-1000, 0], radius=1000 },
	{ material = 1, position=[0, 0.5, -3] },
]
