# samples_per_pixel = 1000

camera = { position = [0, 1, 3], direction = 'forward' }

materials = [
    { type = 'lambert', albedo = 'gray_33' },
    { type = 'lambert', albedo = 'fuchsia' },
    { type = 'metal',   albedo = 'white',     roughness = 0.05 },
    { type = 'dielectric',   albedo = 'alice_blue', roughness = 0.05},

]

planes = [
    #{ material = 0 }
]

spheres = [
    { material = 0, position = [0 ,-1000, 0], radius = 1000 },
    { material = 1, position = [0, 0.5, 0] },
    { material = 2, position = [1, 0.5, 0] },
    { material = 3, position = [0.5, 1.25, 0] },

]
