namespace = 'rt'
doxygen = false

[structs.spheres]
static_variables = [{name = 'kek', value = [1, 2.0, "3"]}]
variables = [
	{ name = 'center_x', type = 'float', alignment = 32 },
	{ name = 'center_y', type = 'float', alignment = 32 },
	{ name = 'center_z', type = 'float', alignment = 32 },
	{ name = 'radius',   type = 'float', alignment = 32 },
]

[structs.vertices]
variables = [
	{ name = 'position_x', type = 'float', alignment = 32 },
	{ name = 'position_y', type = 'float', alignment = 32 },
	{ name = 'position_z', type = 'float', alignment = 32 },
	{ name = 'normal_x',   type = 'float', alignment = 32 },
	{ name = 'normal_y',   type = 'float', alignment = 32 },
	{ name = 'normal_z',   type = 'float', alignment = 32 },
]
