namespace = 'rt'

[hpp]
includes.internal = [ 'common.hpp', 'colour.hpp' ]

[structs.materials]
variables = [
    { name = 'name',         type = 'std::string' },
    { name = 'type',         type = 'material_type' },
    { name = 'albedo',       type = '{% namespace::scope %}colour' },
    { name = 'roughness',    type = 'float' },
    { name = 'reflectivity', type = 'float' },
]

[structs.planes]
variables = [
	{ name = 'value',    type = 'plane' },
	{ name = 'material', type = 'unsigned',  alignment = 32 },
	{ name = 'normal_x', type = 'float',     alignment = 32 },
	{ name = 'normal_y', type = 'float',     alignment = 32 },
	{ name = 'normal_z', type = 'float',     alignment = 32 },
	{ name = 'd',        type = 'float',     alignment = 32 },
]

[structs.spheres]
variables = [
	{ name = 'value',    type = 'sphere' },
	{ name = 'material', type = 'unsigned',  alignment = 32 },
	{ name = 'center_x', type = 'float',     alignment = 32 },
	{ name = 'center_y', type = 'float',     alignment = 32 },
	{ name = 'center_z', type = 'float',     alignment = 32 },
	{ name = 'radius',   type = 'float',     alignment = 32 },
]

[structs.boxes]
variables = [
	{ name = 'value',    type = 'box' },
	{ name = 'material', type = 'unsigned', alignment = 32 },
	{ name = 'center_x', type = 'float',    alignment = 32 },
	{ name = 'center_y', type = 'float',    alignment = 32 },
	{ name = 'center_z', type = 'float',    alignment = 32 },
	{ name = 'extents_x', type = 'float',   alignment = 32 },
	{ name = 'extents_y', type = 'float',   alignment = 32 },
	{ name = 'extents_z', type = 'float',   alignment = 32 },
]
